# Generated by Django 3.2.3 on 2021-06-01 12:01

from django.db import migrations
from top.models import Cities

def fill_in_cities(apps, schema_editor):
    cities = ['Toronto', 'Calgary', 'Edmonton', 'Vancouver', 'Winnipeg',
              'Ottawa', 'Saskatoon', 'Halifax', 'Hamilton', 'Victoria']
    for city in cities:
        b = Cities(name=city)
        b.save()

class Migration(migrations.Migration):

    dependencies = [
        ('top', '0002_cities'),
    ]

    operations = [
        migrations.RunPython(fill_in_cities),
    ]
