# Generated by Django 3.2.3 on 2021-06-01 19:27

from django.db import migrations
from top.models import Languages

def fill_in_languages(apps, schema_editor):
    languages = ['Python', 'Java', 'Kotlin', 'Swift', 'C#', 'C++', 'PHP',
              'JavaScript', 'Scala', 'Ruby']
    for language in languages:
        c = Languages(name=language)
        c.save()

class Migration(migrations.Migration):

    dependencies = [
        ('top', '0003_auto_20210601_1201'),
    ]

    operations = [
        migrations.RunPython(fill_in_languages),
    ]
