# Generated by Django 3.2.3 on 2021-06-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0004_auto_20210601_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityLangVac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_lang', models.IntegerField()),
                ('id_city', models.IntegerField()),
                ('vacancies_number', models.IntegerField()),
            ],
        ),
    ]
